name: geoflutterfire_plus
description: geoflutterfire_plus enables your flutter app to store and query cloud firestore documents based on their geographic location.
version: 0.0.29
homepage: https://github.com/KosukeSaigusa/geoflutterfire_plus

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.10.0'

dependencies:
  cloud_firestore: ^5.2.1
  flutter:
    sdk: flutter
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^2.4.11
  cloud_firestore_platform_interface: ">=6.3.1"
  # fake_cloud_firestore: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
